postprocessor:
  name: odin
  APS_mode: True
  postprocessor_args:
    temperature: 1000
    noise: 0.0014
  postprocessor_sweep:
    temperature: [1, 10, 100, 1000]
    noise: [0.0014, 0.0028, 0.0042, 0.0056, 0.0070, 0.0084, 0.0098]
